server:
  # 端口
  port: 8081
#
#  servlet:
#    context-path: /

spring:
  #  application:
  #    name: news-portal-api
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gmdnews_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Mybatis-plus配置
mybatis-plus:
  #  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  #  type-aliases-package: com.xh.pojo
  global-config:
    db-config:
      #表名前缀
      #      table-prefix: tb_
      # id生成策略 auto为数据库自增
      id-type: auto
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
    #日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#logging:
#  level:
#    com.szl.yeb.mapper: debug


